/*! Copyright © 2015, 2016, Oracle and/or its affiliates. All rights reserved. */
/*! mmpackage v1.10 */
/*! jQuery v1.11.2 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
/*v1.10.21.2596*/
'use strict';(function(){function ca(q,Y,Z){ca=void 0;eval(q)}var q=window.console||{log:function(){},error:function(){}};(function(){function V(a,e,h){var m=[],z;for(z in a)a.hasOwnProperty(z)&&(h?m=m.concat(e(a[z])):m.push(e(a[z])));return m}function Y(a,e){var h=[],m;for(m in a)a.hasOwnProperty(m)&&e(a[m])&&h.push(a[m]);return h}function Z(a,e){var h=void 0,m;for(m in a)if(a.hasOwnProperty(m)&&!0===e(a[m])){h=a[m];break}return h}function da(a,e){if(I(e))return!!Z(a,e);for(var h=a.length;h--;)if(a[h]===e)return!0;
return!1}function W(a,e,h){h=h||0;for(var m=a.length;h<m;h++)if(a[h]===e||I(e)&&e(a[h]))return h;return-1}function I(a){return"function"===typeof a}function P(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function F(a){return"string"===typeof a}function C(a){return"undefined"===typeof a}function R(a){return"number"===typeof a}function aa(a){if(null===a||"object"!==typeof a)return a;var e=a.constructor(),h;for(h in a)a.hasOwnProperty(h)&&(e[h]=aa(a[h]));
return e}function T(a,e){a=C(a)?{}:a;e=C(e)?{}:e;if(null===e||"object"!==typeof e)return e;var h={},m;if("object"===typeof a)for(m in a)a.hasOwnProperty(m)&&(h[m]=a[m]);for(m in e)e.hasOwnProperty(m)&&(h[m]?P(h[m])&&P(e[m])?h[m]=h[m].concat(e[m]):h[m]=T(h[m],e[m]):h[m]=e[m]);return h}function J(a){return C(a)||null==a?!0:1>a.replace(/\s/g,"").length}function ga(a){return a="mm_style"+(a?"_"+a:"")+("_"+ha++)}function K(a){return a.replace(/^\s+|\s+$/gm,"")}function A(){var a=arguments,e={},h=1;F(a[1])||
(e=a[1],h=2);for(var m=a[0],a=P(a[2])?a[2]:M(a,h),h=0;h<a.length;h++)e[a[h]]=function(a){return function(){return a.apply(e,arguments)}}(m[a[h]]);return e}function ba(){function a(a){var h,m="";for(h=0;h<a;h++)m+=(16*Math.random()%16|0).toString(16);return m}return a(8)+"-"+a(4)+"-4"+a(3)+"-"+a(4)+"-"+a(12)}function O(a,e){for(var h in a)a.hasOwnProperty(h)&&e(a[h],h)}function ia(a){return function(){try{a()}catch(e){q.log(e.message||e)}}}function ea(a){var e=a.getAttribute("href");return{hrefHasJS:/(^| )javascript:/i.test(e),
sameSite:a.hostname===window.location.hostname,notRequiresReload:"_blank"===a.target||/^#|(^| )javascript: ?void/i.test(e)}}function fa(a){for(;a&&"a"!==a.tagName.toLowerCase();)a=a.parentElement;return a}function M(a,e,h){h=C(h)?a.length:h;e=e||0;if(P(a))return Array.prototype.slice.call(a,e,h);var m=[],z=(h||0)-e;if(0<z)for(m=Array(z),h=0;h<z;h++)m[h]=a[e+h];return m}function ja(){return function(){}}function N(a){a=a||{};var e="";C(a.opacity)||(a.filter="alpha(opacity="+100*a.opacity+")");O(a,
function(a,m){e+=m+": "+a+" !important; "});return K(e)}function ka(a,e,h){function m(b){if(!k[b]){var c=e[b],d={};try{c(d,z.requireClass,z.require),d.exports=z.options.isDlpEnabled?d.dlp||d.exports:d.basic||d.exports}catch(a){q.log("ERROR: "+a.message+" in module "+b)}f[b]&&(d.exports=d.exports.extend(f[b]));k[b]=d}return k[b]}var z=this,k,l,f;z.options=h||{};f=z.options.moduleExtensions||{};this.reset=function(b){k={};l=b||{}};z.reset(a);this.require=function(b,c){m(b);var d=k[b];return d&&d.config&&
d.config.singleton?(l[b]||(l[b]=new d.exports(z.options)),l[b]):new d.exports(c)};this.requireClass=function(b){m(b);return k[b].exports};this.addModule=function(b,c){e[b]=c}}var la=ca,ha=1,ma={CGApi:function(a,e,h){a.config={singleton:!0};a.exports=function(){function a(b,c,d,p){var g=f.getParam("uv",p)||{};b=K(b);g[b]=g[b]||[];if(void 0===c)c=1;else if(""===c||isNaN(c))c=0,d="NaN";g[b].push(c+(d?","+encodeURIComponent(d):""));f.setParam("uv",g,p)}function e(b,c,d,a){var g=f.getParam("uat",d)||{};
g[K(b)]=K(c+"");f.setParam("uat",g,d,a)}function k(b,c){var d=f.getParam("rul",c)||[],a=V(b,function(b){return encodeURIComponent(C(b)?"":b)}).join(",")+";";d.push(a);f.setParam("rul",d,c)}function l(b,c,d,a){var g=f.getParam("ids",d)||{};g[b+""]=c+"";f.setParam("ids",g,d,a)}var f=h("Engine");this.setAction=function(b,c,d){a(b,c,d,f.storeStrategy.request)};this.postAction=function(b,c,d){a(b,c,d,f.storeStrategy.deferredRequest)};this.setAttr=function(b,c){e(b,c,f.storeStrategy.request)};this.storeAttr=
function(b,c,d){e(b,c,f.storeStrategy.persistent,d)};this.getAttr=function(b){return(f.getParam("uat",f.storeStrategy.persistent)||{})[K(b)]};this.removeAttr=function(b){var c=f.getParam("uat",f.storeStrategy.persistent)||{};delete c[K(b)];f.setParam("uat",c,f.storeStrategy.persistent,365)};this.setId=function(b,c){l(b,c,f.storeStrategy.request)};this.storeId=function(b,c,d){l(b,c,f.storeStrategy.persistent,d)};this.removeId=function(b){var c=f.getParam("ids",f.storeStrategy.persistent)||{};delete c[b+
""];f.setParam("ids",c,f.storeStrategy.persistent,365)};this.hasActions=function(){var b=f.getParam("uv",f.storeStrategy.request)||{},c=f.getParam("uv",f.storeStrategy.deferredRequest)||{};return b&&"{}"!==JSON.stringify(b)||c&&"{}"!==JSON.stringify(c)};this.request=function(b,c){f.setParam("pageid",b,f.storeStrategy.request);f.CGRequest(c)};this.setData=function(b,c,d){f.setData(b,c,d)};this.getData=function(b){return f.getData(b)};this.clearData=function(b){f.clearData(b)};this.getServerAttrs=function(){return f.getServerAttrs()};
this.setCategoryFilter=function(b,c,d){k({categoryId:b,categoryName:c,including:d?1:0},f.storeStrategy.request)};this.setProductFilter=function(b,c,d){k({categoryId:b,productId:c,including:d?1:0,isProduct:1},f.storeStrategy.request)}}},Class:function(a,e,h){e=function(){};e.extend=function(a){var e=function(){e.superclass.constructor.apply(this,arguments);var k={};O(this,function(f,b){k[b]=f});this.base=k;return a.apply(this,arguments)},k=function(){};k.prototype=this.prototype;e.prototype=new k;
e.prototype.constructor=e;e.superclass=this.prototype;e.implementation=a;e.extend=this.extend;e.inherit=this.inherit;return e};e.inherit=function(a){(a.implementation||a).call(this.prototype)};a.exports=e},Cookies:function(a,e,h){a.config={singleton:!0};a.exports=function(a){var e=this,k=a.cookieDomain,l=a.isBaseStorageSecure,f=encodeURIComponent,b=decodeURIComponent;this.set=function(b,d,a){if(!b||!F(b))return q.error("You can't use cookies.set without specifying cookie name."),this;a=a||{};a.secure=
C(a.secure)?l:a.secure;var g=";domain="+(a.domain||k),e=";path="+(a.path||"/"),m;if(a.expires){m=a.expires;var h=new Date;h.setTime(h.getTime()+864E5*m);m=";expires="+h.toGMTString()}else m="";a=a.secure?";secure":"";document.cookie=f(b)+"="+f(d)+g+e+m+a;return this};this.remove=function(b,d){if(!b||!F(b))return q.error("You can't use cookies.remove without specifying cookie name."),this;d||(d={});d.expires=-1;var a=this.get(b);C(a)||this.set(b,"",d);return this};this.get=function(c){if(!c||!F(c))return q.error("You can't use cookies.get without specifying cookie name."),
this;c=new RegExp("(?:^|; )"+f(c).replace(/([.$?*|{}()\[\]\\\/+^])/g,"\\$1")+"((;|$)|(=([^;]*)))");return(c=document.cookie.match(c))?b(c[4]||""):void 0};this.getWrapper=function(){return A(e,"get","set","remove")}}},Events:function(a,e,h){a.config={singleton:!1};var m=e("Class").extend(function(){function a(b,d){var f=b.split("."),g;if(1===f.length)g=f[0];else if(2===f.length){g=f[0];if(0===g.length||-1!==g.indexOf("*"))return!1;g=f[1]}else return!1;if(!g.length)return!1;if(-1!==g.indexOf("*"))if(d){if("*"!==
g)return!1}else return!1;return f}function k(c,d,a,g){b[c]={event_data:d,callback:!0===g?a:void 0};if(f[c]){c=f[c];for(g=0;g<c.length;g++)c[g].call(l,d);I(a)&&a()}}var l=this,f={},b={};this.on=function(c,d,k){if(!F(c))return q.log("eventName is incorrect"),this;if(!a(c,!0))return q.error("'"+c+"' is incorrect for On"),this;if(k&&(k=b[c])){try{d.apply(l,k.event_data)}catch(g){}k.callback&&k.callback()}f[c]=f[c]||[];f[c].push(d);return this};this.off=function(b,a){if(!F(b))return q.log("eventName is incorrect"),
this;f[b]=f[b]||[];for(var k=f[b].length;k--;)a==f[b][k]&&f[b].splice(k,1);return this};this.trigger=function(b,d,f,g){if(!F(b))return q.log("eventName is incorrect"),this;var l=a(b,!1);if(!l)return q.error("'"+b+"' is incorrect for Trigger"),this;k(b,d,f,g);2==l.length&&k(l[0]+".*",d,f,g);return this};this.getWrapper=function(){return A(l,{},"on","off","trigger")}});e=m.extend(function(){var a=this;this.domReady=function(){var a=!1,l=[],f=function(){document.addEventListener?(document.removeEventListener("DOMContentLoaded",
b,!1),window.removeEventListener("load",b,!1)):(document.detachEvent("onreadystatechange",b),window.detachEvent("onload",b))},b=function(){if(document.addEventListener||"load"===event.type||"complete"===document.readyState)f(),c()},c=function(){if(!a){if(!document.body)return setTimeout(c);a=!0;for(var b=0;b<l.length;b++)try{(0,l[b])()}catch(d){q.log(d)}}};if("complete"===document.readyState)c();else if(document.addEventListener)document.addEventListener("DOMContentLoaded",b,!1),window.addEventListener("load",
b,!1);else{document.attachEvent("onreadystatechange",b);window.attachEvent("onload",b);var d=!1;try{d=null==window.frameElement&&document.documentElement}catch(e){}d&&d.doScroll&&function v(){if(!a){try{d.doScroll("left")}catch(b){return setTimeout(v,50)}f();c()}}()}return function(b){b=b||function(){};if(a){try{b()}catch(c){q.log(c)}return!0}l.push(b);return!1}}();this.getWrapper=function(){return A(a,a.base.getWrapper(),"domReady")}});m=m.extend(function(){var a=this,k=h("Dlp");this.domReady=function(a){return k.parentReady(a)};
this.getWrapper=function(){return A(a,a.base.getWrapper(),"domReady")}});a.basic=e;a.dlp=m},Deferred:function(a,e,h){function m(a,l){a=a||{};for(var f in l)l.hasOwnProperty(f)&&(a[f]="object"===typeof l[f]?m(a[f],l[f]):l[f]);return a}function z(a){for(var l=[["resolve","done",[],"resolved"],["reject","fail",[],"rejected"],["notify","progress",[]]],f="pending",b={state:function(){return f},always:function(){c.done(arguments).fail(arguments);return this},then:function(){var a=arguments;return z(function(d){for(var f=
0;f<l.length;f++)(function(a,f){c[l[a][1]](function(){var t=I(f[a])&&f[a].apply(this,arguments);if(t&&I(t.promise))t.promise().done(d.resolve).fail(d.reject).progress(d.notify);else d[l[a][0]+"With"](this===b?d.promise():this,f[a]?[t]:arguments)})})(f,a);a=null}).promise()},promise:function(a){return null!=a?m(a,b):b}},c={},d,e,g=0;g<l.length;g++)(function(a){var g=l[a],k=g[2];b[g[1]]=function(){for(var a=0;a<arguments.length;a++)(function(a){I(a)?f===g[3]?a.apply(d,e):k.push(a):a&&a.length&&"string"!==
typeof a&&b[g[1]].apply(this,a)})(arguments[a]);return this};c[g[0]]=function(){c[g[0]+"With"](this===c?b:this,arguments);return this};c[g[0]+"With"]=function(b,a){if("pending"==f)for(d=b,e=a,g[3]&&(f=g[3]);k.length;)k.shift().apply(b,a);return this}})(g);b.promise(c);a&&a.call(c,c);return c}a.exports=z},When:function(a,e,h){var m=e("Deferred");a.exports=function(){var a=0,k=I(arguments[0]),l=k?[m()]:arguments,f=Array.prototype.slice.call(l),b=f.length,c=1!==b||l[0]&&I(l[0].promise)?b:0,d=1===c?l[0]:
m(),e=function(b,a,f){return function(t){a[b]=this;f[b]=1<arguments.length?Array.prototype.slice.call(arguments):t;f===g?d.notifyWith(a,f):--c||d.resolveWith(a,f)}},g,h,L;if(k)l=arguments,L=setInterval(function(){l[0]()?d.resolve():l[1]&&I(l[1])&&l[1]()&&d.reject()},50),d.always(function(){clearInterval(L)});else if(1<b)for(g=Array(b),k=Array(b),h=Array(b);a<b;a++)f[a]&&I(f[a].promise)?f[a].promise().done(e(a,h,f)).fail(d.reject).progress(e(a,k,g)):--c;c||d.resolveWith(h,f);return d.promise()}},Renderer:function(a,
e,h){a.config={singleton:!1};var m=0,z=0,k=e("Class").extend(function(a){function b(){H&&(clearTimeout(H),H=null);R(t)&&(H=setTimeout(function(){d.showAll()},t))}function c(t){if(t=(t?(t.Name||t)+"":"").toLowerCase()){var b=(a.getElement(t)||{}).Data;if(b)for(var c="",H="",d=0;d<b.length;d++)"Css"===b[d].Type?c=b[d].Data:"Html"===b[d].Type&&""!==K(b[d].Data)?H=b[d].Data:"Script"===b[d].Type&&(L.runElementScript(a,t,{html:H,css:c},b[d].Data),H=c="")}else q.log("renderElement should receive element or elementName")}
var d=this,k=e("When"),g=e("Deferred"),l=h("CGApi"),L=h("Engine"),y=h("Dom"),n={},G=z++,t=7E3,H;this.hide=function(t,a){if(!t)return q.log("You can't use renderer.hide without params"),this;-1===t.indexOf("{")&&(t+="{position:relative;left:-10000px;top:-10000px;}");a=(a||"gen_"+m++)+"_"+G;n[a]=!0;y.addCss(t,a);b();return this};this.show=function(t){if(!t)return q.log("You can't use renderer.show without params"),this;var b=t+"_"+G;if(!n[b])return q.log("ID ("+t+") you try to show is not found"),this;
delete n[b];y.removeCss(b);return this};this.showAll=function(){var t=[];O(n,function(b,a){t.push(a)});y.removeMultiCss(t);n={};H&&(clearTimeout(H),H=null);return this};this.unhideAfter=function(a){"never"===a||R(a)&&0<=a?(t=a,b()):q.log('You can use renderer.unhideAfter with number greater 0 or "never" string only.');return this};this.getContent=function(t){var b=g();l.request(t||a.getName(),function(t){t?b.resolve():b.reject()});return b.promise()};this.runVariantJs=function(t){if(0<arguments.length)c(t);
else for(var b=a.getElements(),H=0;H<b.length;H++)c(b[H]);return this};this.waitUntilDom=function(t){return k(t,L.events.domReady)};this.when=function(){return k.apply(d,arguments)}}),l=k.extend(function(a){var b=e("When"),c=h("Engine");this.waitForElement=function(a){return b(function(){return null!=document.querySelector(a)},c.events.domReady)}}),k=k.extend(function(a){var b=e("When"),c=e("Deferred"),d=h("Engine"),k=h("Dlp");this.waitForElement=function(a){var f=new c,l=!1,e=function(b){l=b};b(function(){k.checkNodeExist(a).done(e);
return l},d.events.domReady).done(function(){f.resolve()}).fail(function(){k.checkNodeExist(a).done(e).then(function(b){b?f.resolve():f.reject()},function(){f.reject()})});return f.promise()}});a.dlp=k;a.basic=l},Campaign:function(a,e,h){var m=e("Element");a.exports=function(a){function k(b){return function(a){return a.Name===b}}var l=this,f=h("Site"),b=a.Name,c=h("BaseStorage",{namespace:b}),d={},e=V(a.Elements,function(b){return new m(b)}),g=a.Recommendations;this.updateData=function(b){for(var a=
0;a<b.Elements.length;a++){var c=W(e,k(b.Elements[a].Name));0<=c?e[c]=new m(b.Elements[a]):e.push(new m(b.Elements[a]))}g=b.Recommendations};this.getElements=function(){return e};this.getRecommendations=function(){return g};this.getExperience=function(){var a=f.getPageExperiences()[b],c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};this.getElement=function(b){b||q.log("You can't use campaign.getElement without params");b=b.toLowerCase();return Z(e,k(b))||null};this.getStyles=function(b){return V(e,
function(a){return a.getStyles(b)},!0)};this.isDefault=function(){if(!e||0==e.length)throw Error("There is no content for campaign "+b+".");for(var a=!0,c=0;c<e.length;c++)a=a&&"Default"===e[c].VariantName;return a};this.getName=function(){return b};this.setData=function(b,a,d){c.set(b,a,d)};this.getData=function(b){return c.get(b)};this.clearData=function(b){c.set(b,null,-1)};this.events=h("Events");this.getContext=function(){var b={};b.scope=d;b.isDefault=function(){return l.isDefault()};b.getElements=
function(){for(var b={},a=0;a<e.length;a++)b[e[a].Name]=e[a].clone();return b};b.getElement=function(b){return(b=l.getElement(b))?b.clone():b};b.getRecommendations=function(){return V(g,aa)};b.getStyles=function(b){return l.getStyles(b)};b.getExperience=function(){return l.getExperience()};b.getName=function(){return l.getName()};b.events=l.events;b.setData=function(b,a,c){return l.setData(b,a,c)};b.getData=function(b){return l.getData(b)};b.clearData=function(b){return l.clearData(b)};return b}}},
Element:function(a,e,h){function m(a){var e=this;e.Name=a.Name;e.HTMLId=a.HTMLId;e.Order=a.Order;e.VariantName=a.VariantName;e.Data=aa(a.Data);this.getStyles=function(a){return V(Y(e.Data,function(f){return"Css"===f.Type&&(C(a)||f.Attrs.id===a)}),function(a){return a.Data})};this.clone=function(){return new m(e)}}a.exports=m},Site:function(a,e,h){a.config={singleton:!0};a.exports=function(){var a=this,e={},k={};this.getPageExperiences=function(){var a,f,b={};for(a in k)if(k.hasOwnProperty(a))for(f in b[a]=
{},k[a])k[a].hasOwnProperty(f)&&(b[a][f]=k[a][f]);return b};this.setPageExperiences=function(a){var f,b,c;for(c in a)if(a.hasOwnProperty(c)){f=a[c];b=k[c];"undefined"===typeof b&&(k[c]={},b=k[c]);for(var d in f)f.hasOwnProperty(d)&&(b[d]=f[d])}return k};this.getContext=function(){var k={};k.scope=e;k.getPageExperiences=a.getPageExperiences;return k}}},Style:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){function a(){var b=l.createElement("style");b.type="text/css";b.media=
"screen";b.id=k.htmlId;var d=l.getElementsByTagName("head")[0];d.insertBefore(b,d.lastChild);return b}function e(){var a="";O(b,function(b){a+=b});return a}var k=this,l=document;k.htmlId=ga("mm_cdApiStyleId");var f=a(),b={};this.set=function(b){(f=l.getElementById(k.htmlId))||(f=a());f.styleSheet?f.styleSheet.cssText=b:f.innerHTML=b};this.add=function(a,d){if(d){if(b[d]){q.error("Style with specified ID("+d+") already exists");return}b[d]=a}else b.nr=b.nr||"",b.nr+=a;k.set(e())};this.remove=function(){O(M(arguments),
function(a){"nr"!==a&&b[a]?delete b[a]:q.error("Could not remove non-existent style "+a+".")});k.set(e())};this.clear=function(){b={};k.set(e())}});a.exports=e},Action:function(a,e,h){a.config={singleton:!0};var m=e("Class").extend(function(){var a=this,k=h("CGApi"),m=e("Deferred");this.sendActions=function(f,b,c){for(var d=!0,e,g,k,m,l=0;l<f.length;l++)m=f[l].name,k=f[l].value,g=f[l].attribute,d&=e=f[l].postponedAction,e?a.postpone(m,k,g):a.set(m,k,g);!d||b?a.send().then(c):c()};this.send=function(a,
b,c){var d=m();if(0<arguments.length&&a&&F(a))k.setAction(a,b,c);else if(0!==arguments.length){q.log("You can't use action.send without setting action name");return}k.hasActions()?k.request("mmevents",function(b){b?d.resolve():d.reject()}):d.resolve();return d.promise()};this.postpone=function(a,b,c){if(!a||!F(a))return q.log("You can't use action.postpone without setting action name."),this;k.postAction(a,b,c);return this};this.set=function(a,b,c){if(!a||!F(a))return q.log("You can't use action.set without setting action name."),
this;k.setAction(a,b,c);return this};this.trackClicks=function(f,b,c){h("Dom").trackClicks(f,b,c,a.sendActions)};this.getWrapper=function(){return A(a,"send","postpone","set","trackClicks")}});a.exports=m},Visitor:function(a,e,h){a.config={singleton:!0};var m=e("Class").extend(function(){var a=this,m=e("Deferred"),f=h("CGApi");this.setAttr=function(a,c){f.setAttr(a,c);return this};this.storeAttr=function(a,c){f.storeAttr(a,c,365);return this};this.getAttr=function(a){return f.getAttr(a)};this.removeAttr=
function(a){f.removeAttr(a);return this};this.setId=function(a,c){f.setId(a,c);return this};this.storeId=function(a,c){f.storeId(a,c,365);return this};this.removeId=function(a){f.removeId(a);return this};this.setData=function(a,c,d){f.setData(a,c,d);return this};this.getData=function(a){return f.getData(a)};this.clearData=function(a){return f.clearData(a)};this.requestPage=function(a){var c=m();f.request(a,function(a){a?c.resolve():c.reject()});return c.promise()};this.getServerAttrs=function(){return aa(f.getServerAttrs())};
this.getWrapper=function(){return A(a,"setAttr","storeAttr","getAttr","removeAttr","setId","storeId","removeId","setData","getData","clearData","requestPage","getServerAttrs")}}),z=m.extend(function(){var a=this;this.navigateTo=function(a){!F(a)||J(a)?q.log("CD API Visitor Module: You should pass targetUrl as a non-empty String to visitor.navigateTo()."):(I(window.stop)?window.stop():document.execCommand("Stop"),window.location.assign(a))};this.getWrapper=function(){return A(a,a.base.getWrapper(),
"navigateTo")}}),m=m.extend(function(){var a=this,e=h("Dlp");this.navigateTo=function(a){!F(a)||J(a)?q.log("CD API Visitor Module: You should pass targetUrl as a non-empty String to visitor.navigateTo()."):e.navigateTo(a)};this.getWrapper=function(){return A(a,a.base.getWrapper(),"navigateTo")}});a.basic=z;a.dlp=m},Dom:function(a,e,h){a.config={singleton:!0};var m=e("Class").extend(function(){function a(t,H,d){return function(){var a=p.getElements(H[0]);if(a.length)return H[0]=a,t.apply(b,H),d(),
!0}}function m(){q=setInterval(function(){for(var a=0;a<z.length;a++)z[a]()&&(z.splice(a,1),--a);z.length||clearInterval(q)},200);d.registerLoop(q)}function f(a,b){if(b&&!d.isVcbActive){var c=p.autoHide(a);return function(){p.removeCss(c)}}return ja()}var b=this,c=e("Deferred"),d=h("Vcb"),p=h("DomPlain"),g=[],z=[],q,y="hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml insertHtmlAbove insertHtmlBelow insertHtmlWithin".split(" "),
n=["addCss","removeCss"],G=["addListener","removeListener","getNodesAttribute","setNodesAttribute"];this.loop=function(t,H){return function(){var d=arguments[0],c=M(arguments),e=p.getElements(d);e.length?(c[0]=e,t.apply(b,c)):F(d)&&(d=f(d,!H),z.length||m(),z.push(a(t,c,d)))}};(function(a,d,c){d=d||{};O(c,function(c){d[c]=b.loop(a[c])})})(p,b,y);A(p,b,n);this.addListener=function(a,b,d){a=p.getElements(a);for(var c=0;c<a.length;c++){var f=p.addEvent(a[c],b,d);g.push({handler:d,handlerWrapper:f})}};
this.removeListener=function(a,b,d){a=p.getElements(a);for(var c=0;c<a.length;c++)for(var f=0;f<g.length;f++)g[f].handler===d&&p.removeEvent(a[c],b,g[f].handlerWrapper)};this.trackClicks=b.loop(p.trackClicks,!0);this.removeMultiCss=p.removeMultiCss;this.getNodesAttribute=function(){var a=M(arguments);a[0]=p.getElements(a[0]);var b=new c;b.resolve(p.getNodesAttribute.apply(p,a));return b.promise()};this.setNodesAttribute=function(){var a=M(arguments);a[0]=p.getElements(a[0]);p.setNodesAttribute.apply(p,
a)};this.getWrapper=function(){var a=A(b,{},G);A(b,a,y);A(p,a,n);return a}}),z=e("Class").extend(function(){var a=this,e=h("Dlp"),f="addCss removeCss hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml setNodesAttribute insertHtmlAbove insertHtmlBelow insertHtmlWithin".split(" "),b=["getNodesAttribute"],c=["addListener","removeListener"];this.addListener=function(a,b,c){e.addListener(a,
b,c)};this.removeListener=function(a,b,c){e.removeListener(a,b,c)};O(f,function(b){a[b]=e.proxy("Dom",b)});O(b,function(b){a[b]=e.proxy("Dom",b,!0)});this.trackClicks=function(a,b,c,f){e.trackClicks(a,b,c,f)};this.removeMultiCss=e.proxy("Dom","removeMultiCss");this.getWrapper=function(){var d=A(a,{},f);A(a,d,b);A(a,d,c);return d}});a.basic=m;a.dlp=z},DomPlain:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){function a(b,c){return window.getComputedStyle?window.getComputedStyle(b,
null)[c]:b.currentStyle?b.currentStyle[c]:b.style[c]}function e(a,b,c){R(c)?b[c]&&a.push(b[c]):a=a.concat(M(b));return a}function k(a,b){return(a.matches||a.matchesSelector||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector).call(a,b)}function l(a,b){for(var c=a.split(":eq("),d=[],f,g,m,h,l=0;l<c.length;l++){h=/^(?:\d+\))?\s*(>)?(\+)?\s*(.+)?/.exec(c[l]);f=h[3];if(!f)break;h=h[1]?"direct":h[2]?"next":"querySelector";for(m=(g=c[l+1]&&/^(\d+)\)(.+)?/.exec(c[l+1]))?g[1]:null;"querySelector"!==
h;)g=f.match(/([^ >]+)( \d+)?\s*(>?)(\+?)\s*(.*)/),f=g[5],d.push({selector:g[2]?g[1]+g[2]:g[1],findingType:h}),h=g[3]?"direct":g[4]?"next":"querySelector";f&&d.push({selector:f,findingType:h});m&&(d[d.length-1].index=parseInt(m,10))}c=P(b)?b:[b];for(f=0;f<d.length;f++){l=[];if("querySelector"===d[f].findingType)for(h=0;h<c.length;h++){g=d[f].index;m=[];for(var G=c[h].querySelectorAll(d[f].selector),p=0;p<G.length;p++)n.useZindex(G[p])&&m.push(G[p]);l=e(l,m,g)}else if("direct"===d[f].findingType)for(m=
0;m<c.length;m++){if(g=[],h=c[m].children){for(G=0;G<h.length;G++)1===h[G].nodeType&&k(h[G],d[f].selector)&&g.push(h[G]);l=e(l,g,d[f].index)}}else if("next"===d[f].findingType)for(g=0;g<c.length;g++)(h=c[g].nextSibling)&&1===h.nodeType&&k(h,d[f].selector)&&(l=e(l,[h],d[f].index));c=l}return M(c)}function f(a,b){var c=[],d=Object.prototype.toString.call(a);if(F(a)){for(var c=b||document,d=a.split(","),f=[],e=0;e<d.length;e++)d[e]=d[e].replace(/^\s+/g,"").replace(/\s+$/g,""),d[e]&&(f=f.concat(l(d[e],
c)));c=f}else"[object Array]"===d||"[object NodeList]"===d||"[object HTMLCollection]"===d?c=M(a):c[0]=a;return c}function b(a){return a.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,"").replace(/<title\b[^<]*(?:(?!<\/title>)<[^<]*)*<\/title>/gi,"").replace(/<link\b[^<]*>/gi,"").replace(/<meta\b[^<]*>/gi,"")}function c(a,b){for(var c=(a.style.cssText.replace(/[^;]$/,"$0;")+b).split(";"),d={},f=0;f<c.length;f++)if(c[f]){var e=c[f].split(":");d[e[0].replace(/\s/g,"")]=e[2]?e[1]+":"+e[2]:
e[1]}var c="",g;for(g in d)d.hasOwnProperty(g)&&(c+=g+":"+d[g]+"; ");y.setCssText(a,c.replace(/\s$/,""))}function d(b,d,f){var e=a(b,"position");d=d?parseInt(d,10):0;f=f?parseInt(f,10):0;if("relative"===e||"absolute"===e||"fixed"===e){var g=a(b,"left"),n=a(b,"right");"auto"===g&&"auto"!==n?d="right: "+(parseInt(n,10)-d)+"px !important; ":("auto"===g?g=d:"relative"===a(b,"position")?g=parseInt(g,10)+d:(g=parseInt(b.offsetLeft,10)+d,d=a(b,"margin-left"),"auto"!==d&&(g-=parseInt(d,10))),d="left: "+g+
"px !important; ");g=a(b,"top");n=a(b,"bottom");"auto"===g&&"auto"!==n?f="bottom: "+(parseInt(n,10)-f)+"px !important; ":("auto"===g?g=f:"relative"===a(b,"position")?g=parseInt(g,10)+f:(g=parseInt(b.offsetTop,10)+f,f=a(b,"margin-top"),"auto"!==f&&(g-=parseInt(f,10))),f="top: "+g+"px !important; ")}else e="relative",d="left: "+d+"px !important; ",f="top: "+f+"px !important; ";c(b,d+f+("position: "+e+" !important;"))}function p(a,c){C(c.imageUrl)||"img"!==a.tagName.toLowerCase()||(a.style.visibility=
"hidden",a.src=c.imageUrl,y.addEvent(a,"load",function(){a.style.visibility=""}));C(c.imageAlt)||a.setAttribute("alt",b(c.imageAlt));C(c.imageTitle)||a.setAttribute("title",b(c.imageTitle))}function g(a){var b,c;b=document.createElement("img");p(b,a);void 0!==a.linkUrl&&(c=document.createElement("a"),c.setAttribute("href",a.linkUrl),c.appendChild(b));return c||b}function v(a,b){return function(){for(var c=b&&[],d=M(arguments),e=f(d[0]),g=0;g<e.length;g++)if(e[g]&&e[g].tagName){d[0]=e[g];var n=a.apply(y,
d);b&&c.push(n)}return c}}function L(a,b){var c=fa(b),d=void 0;if(c){var f=ea(c);if(!f.sameSite){a.originalPreventDefault=a.originalPreventDefault||a.preventDefault;a.preventedByClientsCode=a.preventedByClientsCode||a.defaultPrevented&&!a.preventedByCdApiCode;a.preventDefault=function(){a.preventedByClientsCode=!0;a.originalPreventDefault()};a.originalPreventDefault();a.preventedByCdApiCode=!0;var g=!1,d=function(){g||a.preventedByClientsCode||(f.hrefHasJS?(new Function(c.getAttribute("href"))).call(window):
window.location.assign(c.href),g=!0)};setTimeout(d,2E3)}}return d}var y=this,n=h("Vcb"),G=h("Style");this.setCssText=function(a,b){a.style.cssText=b};this.addCss=function(a,b){if(!P(a)&&!F(a))return q.log("You try call dom.addCss with wrong arguments."),this;0===a.length&&q.log("WARNING: You add empty css.");a.join&&(a=a.join("\n"));G.add(a,b);return this};this.removeCss=function(a){if(!a)return q.log("You can't use dom.removeCss without params"),this;G.remove(a);return this};this.removeMultiCss=
function(a){G.remove.apply(G,a);return this};this.getStyle=a;this.getElements=f;this.updateElementStyle=v(c);this.addEvent=function(a,b,c){var d=function(b){b=b||window.event;!b.target&&b.srcElement&&(b.target=b.srcElement);return c.call(a,b)};a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d);return d};this.removeEvent=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)};this.addClass=function(a,b){b=K(b);var c=
K(a.getAttribute("class")||"");~c.indexOf(b)||a.setAttribute("class",K(c?c+" "+b:b))};this.hide=v(function(a){c(a,"visibility: hidden !important;")});this.show=v(function(a){c(a,"visibility: visible !important;")});this.resize=v(function(a,b,f,g,e){b=parseInt(b,10);f=parseInt(f,10);c(a,"width: "+b+"px !important; height: "+f+"px !important;");(g||e)&&d(a,g,e)});this.freeMove=v(d);this.changeStyle=v(c);this.guidedMove=v(function(a,b){if(0<=b){var c=a.parentElement;c.removeChild(a);var d=c.children;
b<d.length?c.insertBefore(a,d[b]):c.appendChild(a)}});this.remove=v(function(a){var b=a.parentElement;b&&b.removeChild(a)});this.bringToFront=v(function(b,d){if("undefined"===typeof d){for(var f=0,g=0,e=document.querySelectorAll("*"),k=e.length,h=0;h<k;h++)if(f=parseInt(a(e[h],"z-index"),10),!isNaN(f)&&g<f&&n.useZindex(e[h])&&(g=f),n.isVcbActive&&g>=n.maxZindex){g=n.maxZindex-11;break}d=g+10}f=a(b,"position");c(b,"z-index: "+d+" !important; position: "+("static"===f||"auto"===f?"relative":f)+" !important;")});
this.changeLinkUrl=function(a,b){y.setNodesAttribute(a,"href",b)};this.insertImageBannerAbove=v(function(a,b){var c=g(b);a.parentElement.insertBefore(c,a)});this.insertImageBannerBelow=v(function(a,b){var c=g(b);a.parentElement.insertBefore(c,a.nextSibling)});this.insertImageBannerWithin=v(function(a,b){var c=g(b);a.appendChild(c)});this.changeImageBanner=v(function(a,b){if("a"===a.tagName.toLowerCase()){void 0!==b.linkUrl&&a.setAttribute("href",b.linkUrl);for(var c=a.children,d=0;d<c.length;d++)"img"===
c[d].tagName.toLowerCase()&&p(c[d],b)}else"img"===a.tagName.toLowerCase()&&(p(a,b),void 0!==b.linkUrl&&"a"===a.parentElement.tagName.toLowerCase()&&a.parentElement.setAttribute("href",b.linkUrl))});this.editHtml=v(function(a,c){a.innerHTML=b(c)});this.setNodesAttribute=v(function(a,b,c){a.setAttribute(b,c)});this.getNodesAttribute=v(function(a,b){return a.getAttribute(b)},!0);this.insertHtmlAbove=v(function(a,c){var d=document.createElement("div");a.parentElement.insertBefore(d,a);d.outerHTML=b(c)});
this.insertHtmlBelow=v(function(a,c){var d=document.createElement("div");a.parentElement.insertBefore(d,a.nextSibling);d.outerHTML=b(c)});this.insertHtmlWithin=v(function(a,c){var d=document.createElement("div");a.appendChild(d);d.outerHTML=b(c)});this.autoHide=function(a){a=a.replace(/:eq\(\d*\)/gmi,"");var b=ba();y.addCss(a+"{visibility: hidden;}",b);return b};this.trackClicks=v(function(a,b,c,d){function f(){return[b.name,b.value,b.attribute,b.postponedAction]}n.isVcbActive?n.registerClickAction(a,
b,c):(a["data-mm-events-ref"]||(a["data-mm-events-ref"]={lockFuncs:[]},y.addEvent(a,"click",function(a){for(var b=this["data-mm-events-ref"].lockFuncs,c=[],f=0;f<b.length;f++){var g=b[f]();if(g){var e=g[0],t;t=e;var n=a;t=n.target===this?!1:F(n.data)&&da(n.data.split(","),t);t||(c.push({name:e,value:g[1],attribute:g[2],postponedAction:C(g[3])?!0:g[3]}),g=a.data&&F(a.data)?a.data.split(","):[],da(g,e)||(g.push(e),a.data=g.join()))}}if(c.length){var f=fa(this),b=!1,h;if(f){if(!(h=ea(f)).sameSite||h.notRequiresReload)b=
!0}else h=this.nodeName.toLowerCase(),f=this.getAttribute("type"),("input"===h||"button"===h)&&f&&"submit"===f.toLowerCase()||(b=!0);d(c,b,L(a,this))}})),a["data-mm-events-ref"].lockFuncs.push(f))})});a.exports=e},BaseWidget:function(a,e,h){a.config={singleton:!1};e=e("Class").extend(function(a){function e(a,b){for(;a&&a.parentNode;)if(a=a.parentNode,a===b)return!0;return!1}function k(){function a(c){return!c||!R(c.displayedCount)||c.displayedCount>=b.showsCount?1:c.displayedCount+1}var b=g.options.showFrequency;
if(!0!==b.always){var c=new Date,d=g.getWidgetData(),f=d.persistent,d=d.session,e;b.showsInterval&&"session"===b.showsInterval&&(e={lastShown:c,displayedCount:a(d)});c={lastShown:c,wasDismissed:f&&f.wasDismissed||!1,displayedCount:a(f)};g.setWidgetData(c,e)}}function l(){var a=g.getWidgetData(),b=a.persistent;g.setWidgetData({lastShown:b&&b.lastShown,wasDismissed:!0,displayedCount:b&&b.displayedCount},a.session)}function f(){function a(){var b=f.lastShown&&f.lastShown.getTime();if(!J(h)){if("session"===
h)return!d.session;if("campaign"===h)return!d.persistent;var g=new Date,e=g.getMonth(),g=g.getFullYear();if(e={hour:36E5,day:864E5,week:6048E5,month:864E5*(new Date(g,e,0)).getDate()}[h])return c-b>e}}var b=g.options.showFrequency;if(!(!0!==b.always&&b.showsInterval||b.neverAfterDismiss))return!0;var c=new Date,d=g.getWidgetData(),f=d.persistent,e=d.session;if(f&&!0===b.neverAfterDismiss&&!0===f.wasDismissed)return!1;if(!0===b.always||!b.showsInterval)return!0;var h=K(b.showsInterval.toLowerCase()),
b=b.showsCount;if(!J(h)&&b&&R(b)){if("session"===h&&!d.session||!d.persistent)return!0;var k=a();return"session"===h?e.displayedCount<b:f.displayedCount<b||k}}var b=h("CGApi"),c=h("Engine").events,d=h("Dom"),p=h("DomPlain"),g=this,q=!1,L=[],y=[];g.target=document.body;g.selectors={guidAttr:"data-vcb-me-guid",wrapper:"vcb-me-wrapper",overlay:"vcb-me-overlay",contentWrapper:"vcb-me-content-wrapper",content:"vcb-me-content",contentInner:"vcb-me-content-inner",dismiss:"vcb-me-dismiss",pointer:"vcb-me-pointer"};
g.type="BaseWidget";g.wrapper=null;g.contentWrapper=null;g.content=null;g.setWidgetData=function(a,c){var d=g.options.guid;a&&b.setData(d+"persistData",JSON.stringify(a),365);c&&b.setData(d+"sessionData",JSON.stringify(c),0)};g.getWidgetData=function(){var a=g.options.guid,c={persistent:void 0,session:void 0};if(!J(a)){var d=b.getData(a+"sessionData"),a=b.getData(a+"persistData");J(a)||(c.persistent=JSON.parse(a),c.persistent.lastShown=new Date(c.persistent.lastShown));J(d)||(c.session=JSON.parse(d),
c.session.lastShown=new Date(c.session.lastShown))}return c};g.clearWidgetData=function(){var a=g.options.guid;J(a)||(b.clearData(a+"persistData"),b.clearData(a+"sessionData"))};g.validateOptions=function(a){var b=[];a.appearance.name||b.push("Can't create widget! Name parameter required!");a.guid||b.push("Can't create widget! Guid parameter required!");a.content||b.push("Can't create widget! Content is required!");if(b.length)throw Error(b.join("\n"));};g.addClassesAndIdContentElements=function(){for(var a=
g.getContentWrapper(),b=g.options,a=a.firstChild;null!==a&&1!==a.nodeType;)a=a.nextSibling;var c;if(a){a.id||(a.id=b.guid);p.addClass(a,g.selectors.content);if(!J(b.closeEvent.dismissElements))for(c=p.getElements(b.closeEvent.dismissElements,a),b=0;b<c.length;b++)p.addClass(c[b],g.selectors.dismiss);for(b=a.lastChild;null!==b&&1!==b.nodeType;)b=b.previousSibling;!b||c&&~W(c,b)||p.addClass(b,g.selectors.contentInner)}};g.getWrapper=function(){if(e(g.wrapper,g.target))return g.wrapper;var a=p.getElements("["+
g.selectors.guidAttr+'="'+g.options.guid+'"]',g.target)[0];if(a)return a};g.wrapperFor=function(a){return function(){if(!e(g[a],g.target)){var b=g.getWrapper();g[a]=p.getElements("."+g.selectors[a],b)[0]}return g[a]}};g.getContentWrapper=g.wrapperFor("contentWrapper");g.getContent=g.wrapperFor("content");g.bindWidgetShowEvents=function(){var a=function(){f()&&g.show()},b=g.options.displayEvent,d;!0===b.onPageLoad&&c.domReady(a);if(!J(b.initAttachedTo)){var e=p.getElements(b.initAttachedTo);for(d=
0;d<e.length;d++)!0===b.onClick&&p.addEvent(e[d],"click",a),!0===b.onMouseOver&&p.addEvent(e[d],"mouseover",a),!0===b.onMouseOut&&p.addEvent(e[d],"mouseout",a)}if(b.delay){var h=1E3*parseInt(b.delay,10);if(b.startAfterIdle){var k;p.addEvent(document,"ontouchstart"in window?"touchmove":"mousemove",function(){window.clearTimeout(k);k=window.setTimeout(a,h)})}else window.setTimeout(a,h)}b.onLosePageFocus&&(p.addEvent(window,"blur",a),p.addEvent(window,"pagehide",a));b.onViewportMouseOut&&p.addEvent(document,
"mouseout",function(a){(a=a.relatedTarget||a.toElement)&&"html"!==a.nodeName.toLowerCase()||f()&&g.show()});if(!J(b.onCustomEvent))c.on(b.onCustomEvent,a)};g.bindDismissEvents=function(){var a=g.getWrapper(),b=g.options.closeEvent;if(b.onDismissButton&&!J(b.dismissElements))for(a=p.getElements(b.dismissElements,a),b=0;b<a.length;b++)p.addEvent(a[b],"click",g.dismiss)};g.bindCloseEvents=function(){function a(c){var d=p.getElements(g.options.displayEvent.initAttachedTo||""),f=g.getWrapper(),f=p.getElements("*:not(."+
g.selectors.overlay+")",f);if(~W(d,c.target)||~W(f,c.target))return!1;b()}var b=g.hide;g.options.closeEvent.onClickOutside&&(p.addEvent(document,"click",a),p.addEvent(window,"keydown",function(a){27===(C(a.which)?a.keyCode:a.which)&&b()}))};g.show=function(){var a=g.getWrapper();p.show(a);for(a=0;a<L.length;a++)L[a].call(null);q=!0};g.hide=function(){var a=g.getWrapper();d.hide(a);q=!1};g.dismiss=function(){g.hide();for(var a=0;a<y.length;a++)y[a].call(null)};g.destroy=function(){var a=g.getWrapper();
a&&a.parentNode&&a.parentNode.removeChild(a)};g.getOptions=function(){return g.options};g.isShown=function(){return q};g.subscribeFunctionOnImgsLoads=function(a){for(var b=p.getElements("img"),c=0;c<b.length;c++)p.addEvent(b[c],"load",a)};g.init=function(){g.options=g.mergeWithDefaultWidgetOptions(a);g.validateOptions(g.options);y.push(l);L.push(k);g.createWidgetDom();g.bindWidgetShowEvents()}});a.exports=e},Lightbox:function(a,e,h){a.config={singleton:!1};e=e("BaseWidget").extend(function(){function a(){var c=
b.getOverlay(),e=b.options.appearance,g={display:"block",position:"fixed",top:"0px",left:"0px",height:"100%",width:"100%"};e.fadeEnabled?(g["background-color"]=e.fadeColor,g.opacity=parseFloat(e.opacity)):g.opacity=0;f.updateElementStyle(c,N(g))}function e(){var a=b.getContentWrapper(),c=b.options.appearance,g={};g["background-color"]=c.backgroundColor;g.position="fixed";c.autofit?(g.display="inline-block",g.width="auto",g.height="auto"):(g.width=c.width,g.height=c.height);f.updateElementStyle(a,
N(g))}function k(){var a=b.getContentWrapper();f.updateElementStyle(a,N({top:0,left:0}));var c={},e=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,h=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,k=parseInt(f.getStyle(a,"width"),10),m=parseInt(f.getStyle(a,"height"),10),l=(h<m?h-30:m)/2;c.position=h<m+l-60?"absolute":"fixed";c.top="50%";c.left="50%";c["margin-top"]=-1*l+"px";c["margin-left"]=(e<k?e:k)/2*-1+"px";f.updateElementStyle(a,
N(c))}var l=h("Dom"),f=h("DomPlain"),b=this,c=b.base;b.type="Lightbox";b.widgetOverlay=null;b.getOverlay=b.wrapperFor("overlay");b.mergeWithDefaultWidgetOptions=function(a){return T({appearance:{backgroundColor:"#FFFFFF",fadeEnabled:!0,fadeColor:"#000000",opacity:.8,autofit:!0},displayEvent:{},closeEvent:{onDismissButton:!0,onClickOutside:!0},showFrequency:{always:!0,neverAfterDismiss:!0}},a)};b.show=function(){a();e();k();b.subscribeFunctionOnImgsLoads(k);c.show()};b.createWidgetDom=function(){b.wrapper=
document.createElement("div");b.wrapper.setAttribute(b.selectors.guidAttr,b.options.guid);f.addClass(b.wrapper,b.selectors.wrapper);l.hide(b.wrapper);b.target.appendChild(b.wrapper);b.widgetOverlay=document.createElement("div");f.addClass(b.widgetOverlay,b.selectors.overlay);b.wrapper.appendChild(b.widgetOverlay);a();l.bringToFront(b.widgetOverlay);b.contentWrapper=document.createElement("div");f.addClass(b.contentWrapper,b.selectors.contentWrapper);b.wrapper.appendChild(b.contentWrapper);b.contentWrapper.innerHTML=
b.options.content;b.addClassesAndIdContentElements();e();l.bringToFront(b.contentWrapper);b.bindCloseEvents();b.bindDismissEvents()};b.init()});a.exports=e},Notification:function(a,e,h){a.config={singleton:!1};e=e("BaseWidget").extend(function(){var a=h("Dom"),e=h("DomPlain"),k=this,l=k.base;k.type="Notification";k.mergeWithDefaultWidgetOptions=function(a){return T({appearance:{backgroundColor:"#FFFFFF"},displayEvent:{},closeEvent:{onDismissButton:!0},showFrequency:{always:!0}},a)};k.createWidgetDom=
function(){k.wrapper=document.createElement("div");k.wrapper.setAttribute(k.selectors.guidAttr,k.options.guid);e.addClass(k.wrapper,k.selectors.wrapper);a.hide(k.wrapper);k.target.appendChild(k.wrapper);k.contentWrapper=document.createElement("div");e.addClass(k.contentWrapper,k.selectors.contentWrapper);k.contentWrapper.innerHTML=k.options.content;k.wrapper.appendChild(k.contentWrapper);k.addClassesAndIdContentElements();k.bindCloseEvents();k.bindDismissEvents()};k.show=function(){var a=k.getWrapper(),
b,c=k.options.appearance;J(c.insertWithin)?J(c.insertAbove)?J(c.insertBelow)||(b=e.getElements(c.insertBelow)[0])&&b.parentElement.insertBefore(a,b.nextSibling):(b=e.getElements(c.insertAbove)[0])&&b.parentElement.insertBefore(a,b):(b=e.getElements(c.insertWithin)[0])&&b.appendChild(a);if(b){a=k.getContentWrapper();b=k.getContent();var c=k.options.appearance,d={},h={};h["background-color"]=c.backgroundColor;c.autofit?(d.display="inline-block",d.width="auto",d.height="auto"):(d.width=c.width,d.height=
c.height,d["margin-left"]="auto",d["margin-right"]="auto",h.width="100%",h.height="100%");e.updateElementStyle(b,N(h));e.updateElementStyle(a,N(d));l.show()}};k.hide=function(){var a=k.getWrapper();k.target.appendChild(a);l.hide()};k.init()});a.exports=e},Callout:function(a,e,h){a.config={singleton:!1};e=e("BaseWidget").extend(function(){function a(b){return"top"===b}function e(a){return"bottom"===a}function k(a){return"left"===a}function l(a){return"right"===a}function f(a){return"center"===a}function b(a){a=
a.getBoundingClientRect();var b=C(window.pageXOffset)?document.documentElement.scrollLeft:window.pageXOffset,c=C(window.pageYOffset)?document.documentElement.scrollTop:window.pageYOffset,d=a.top+c,f=a.left+b,c=a.bottom+c,b=a.right+b;return{top:d,left:f,bottom:c,right:b,width:a.width||b-f,height:a.height||c-d}}function c(a){var b=(a||"").split(" ");a=K(b[0]||"left").toLowerCase();b=K(b[1]||"top").toLowerCase();return{side:a,part:b}}function d(a){var b=(a||"").split(" ");a=parseInt(b[0]||0,10);b=parseInt(b[1]||
0,10);return{side:a,part:b}}function p(g,h,n,p){function q(){k(x.part)?r.left=w.part:f(x.part)?r.left=u.width/2-S/2+w.part:l(x.part)&&(r.left=u.width-S-w.part)}function v(){a(x.part)?r.top=w.part:f(x.part)?r.top=u.height/2-E/2+w.part:e(x.part)&&(r.top=u.height-E-w.part)}var r={},x=c(n),w=d(p),u={};if("page"===h||"viewport"===h)u.top=u.right=u.bottom=u.left=0,"page"===h?(n=b(document.body),u.width=n.width,u.height=n.height):(u.width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,
u.height=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);if(g=y.getElements(g)[0]){g=b(g);var S=g.width,E=g.height;k(x.side)?(v(),r.left=w.side):l(x.side)?(v(),r.left=u.width-S-w.side):e(x.side)?(q(),r.top=u.height-E-w.side):a(x.side)?(q(),r.top=w.side):f(x.side)&&f(x.part)&&(r.left=u.width/2-S/2+w.side,r.top=u.height/2-E/2+w.part);r.position="viewport"===h?"fixed":"absolute";return r}}function g(g,h,n,p){function q(){a(x.part)?r.top=u.top-w.part:f(x.part)?r.top=
u.top+u.height/2-E/2+w.part:e(x.part)&&(r.top=u.bottom-E+w.part)}function v(){k(x.part)?r.left=u.left-w.part:f(x.part)?r.left=u.left+u.width/2-S/2+w.part:l(x.part)&&(r.left=u.right-S+w.part)}var r={},x=c(n),w=d(p),u={};if(h){h=y.getElements(h)[0];if(!h)return;u=b(h)}if(g=y.getElements(g)[0]){h=b(g);var S=h.width,E=h.height;g=g.offsetParent||document.body;h=y.getStyle(g,"position");if("relative"===h||"absolute"===h||"fixed"===h)g=b(g),u.top-=g.top,u.left-=g.left,u.right=u.left+u.width,u.bottom=u.top+
u.height;k(x.side)?(q(),r.left=u.left-S-w.side):l(x.side)?(q(),r.left=u.right+w.side):a(x.side)?(v(),r.top=u.top-E-w.side):e(x.side)?(v(),r.top=u.bottom+w.side):f(x.side)&&f(x.part)&&(r.left=u.left+u.width/2-S/2+w.part,r.top=u.top+u.height/2-E/2+w.part);r.position="absolute";return r}}function q(){function d(a,b){b=b||"px";var c=["z-index"],f={},e;for(e in a)if(a.hasOwnProperty(e)){var g=a[e];R(g)&&0!==g&&!~W(c,e)&&(g+=b);f[e]=g}return f}function h(a){return{top:"bottom",bottom:"top",left:"right",
right:"left"}[a]}function v(a,b){y.updateElementStyle(a,N(b));y.updateElementStyle(a.children[0],N({width:0,height:0}))}function X(d,g,t,n){function p(b){var c,g="side"===b?"part":"side";a(B[b])||e(B[b])?c=0>d.top&&D.bottom+v.height<q.height||d.top+v.height>q.height&&0<D.top-v.height?h(B[b]):B[b]:l(B[b])||k(B[b])?c=0>d.left&&D.right+v.width<q.width||d.left+v.width>q.width&&0<D.left-v.width?h(B[b]):B[b]:f(B[b])&&(c=a(B[g])||e(B[g])?0>d.left?"right":d.left+v.width>q.width?"left":B[b]:k(B[g])||l(B[g])?
0>d.top?"top":d.top+v.height>q.height?"bottom":B[b]:B[b]);return c}var q={width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},r=C(window.pageXOffset)?document.documentElement.scrollLeft:window.pageXOffset,u=C(window.pageYOffset)?document.documentElement.scrollTop:window.pageYOffset,v=T({},b(t));t=y.getElements(n)[0];var D=b(t),B=c(g);d=T({},d);d.top-=u;d.left-=r;v.top-=
u;v.left-=r;v.bottom-=u;v.right-=r;g=p("side");r=p("part");return g+" "+r}var D=n.getContentWrapper(),G=n.options.appearance,r=n.options.appearance.position,x,w=r.at;x={};y.updateElementStyle(D,N({top:0,left:0}));if("page"===r.relativeTo||"viewport"===r.relativeTo)x=p(D,r.relativeTo,w,r.offset),x=d(x);else if(!J(r.relativeTo)){x=g(D,r.relativeTo,w,r.offset);if(r.viewportDetection){var u=X(x,w,D,r.relativeTo);u!==w&&(w=u,x=g(D,r.relativeTo,w,r.offset))}x=d(x)}y.updateElementStyle(D,N(x));(function(f,
E,p){function q(b){b=a(b)||e(b)?"width":k(b)||l(b)?"height":void 0;b=Math.ceil(3*Math.log(V[b]));return 7>b?7:b}function r(a){var b=A+"px solid "+G.backgroundColor,c=A+"px solid transparent";return T(R,{top:{"border-bottom":b,"border-left":c,"border-right":c},bottom:{"border-top":b,"border-left":c,"border-right":c},right:{"border-top":c,"border-bottom":c,"border-left":b},left:{"border-top":c,"border-bottom":c,"border-right":b}}[a])}function u(a,b){var c=a;b&&2*a>b&&(c=b-a,c=0>c?0:c);return c}var w=
n.getContent(),x=n.getPointer(),X=x&&x.children[0],A,C,J=!1,I=1,K=1,M=0,O=0,Q="0 ",P={},R={width:0,height:0,"border-top":"none","border-bottom":"none","border-left":"none","border-right":"none"};if(E){var U=c(f),V=b(D);C=U.part;"page"===p||"viewport"===p?(F(E)?(p=c(E),f=p.side,C=p.part,J=f!==U.side&&f!==U.part):(f=U.side,E=f+" "+C),K=-1):(f=h(U.side),E=f+" "+C,I=-1,p=y.getElements(p)[0],P=b(p));A=q(f);p=r(f);y.updateElementStyle(x,N(p));p=b(x);U=a(C)||e(C)?u(p.height,P.height):0;P=k(C)||l(C)?u(p.width,
P.width):0;a(f)?(O=p.height,Q+=-P):e(f)?(O=p.height*K*I,Q+=-P):k(f)?(M=p.width,Q+=-U):l(f)&&(M=p.width*K*I,Q+=-U);J||L.freeMove(D,M,O);E=d(g(x,w,E,Q));y.updateElementStyle(x,N(E));X&&(x=X.children[0],E=Math.sqrt(2*Math.pow(A,2)),w={margin:0,padding:0,"box-shadow":y.getStyle(w,"box-shadow"),transform:"rotate(45deg)",position:"absolute","z-index":-1,width:E,height:E},I={position:"absolute",overflow:"hidden",top:-A,left:-A,width:2*p.width,height:2*p.height},M=A-E/2+p.width/2,O=-A-p.width/2,Q=A-E/2+p.height/
2,p=-A-p.height/2,a(f)?(w.top=2*A-E/2,w.left=M,I.left=O):e(f)?(w.top=-E/2,w.left=M,I.left=O):k(f)?(w.top=Q,w.left=2*A-E/2,I.top=p):l(f)&&(w.top=Q,w.left=-E/2,I.top=p),y.updateElementStyle(X,N(d(I))),y.updateElementStyle(x,N(d(w))))}else v(x,R)})(w,r.pointer,r.relativeTo)}var L=h("Dom"),y=h("DomPlain"),n=this,G=n.base;n.type="Callout";n.pointer=null;n.mergeWithDefaultWidgetOptions=function(a){return T({appearance:{backgroundColor:"#FFFFFF",autofit:!0,position:{at:"top left",relativeTo:"viewport"}},
displayEvent:{},closeEvent:{onDismissButton:!0},showFrequency:{always:!0}},a)};n.getPointer=n.wrapperFor("pointer");n.createWidgetDom=function(){n.wrapper=document.createElement("div");n.wrapper.setAttribute(n.selectors.guidAttr,n.options.guid);y.addClass(n.wrapper,n.selectors.wrapper);L.hide(n.wrapper);n.target.appendChild(n.wrapper);n.contentWrapper=document.createElement("div");y.addClass(n.contentWrapper,n.selectors.contentWrapper);n.contentWrapper.innerHTML=n.options.content;n.wrapper.appendChild(n.contentWrapper);
L.bringToFront(n.contentWrapper);n.addClassesAndIdContentElements();n.pointer=document.createElement("span");y.addClass(n.pointer,n.selectors.pointer);y.updateElementStyle(n.pointer,N({width:0,height:0,margin:0,padding:0,display:"inline-block"}));n.contentWrapper.appendChild(n.pointer);var a=document.createElement("div");n.pointerShadow=document.createElement("div");n.pointerShadow.appendChild(a);n.pointer.appendChild(n.pointerShadow);n.bindCloseEvents();n.bindDismissEvents()};n.show=function(){var a=
n.getContentWrapper(),b=n.getContent(),c=n.options.appearance,d={},f={};f["background-color"]=c.backgroundColor;c.autofit?(d.display="inline-block",d.width="auto",d.height="auto"):(d.width=c.width,d.height=c.height,f.width="100%",f.height="100%");f=T(d,f);y.updateElementStyle(b,N(f));y.updateElementStyle(a,N(d));q();n.subscribeFunctionOnImgsLoads(q);G.show()};n.init()});a.exports=e},Widgets:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){var a=this;this.createLightbox=function(a,
e){a.guid=e;h("Lightbox",a)};this.createNotification=function(a,e){a.guid=e;h("Notification",a)};this.createCallout=function(a,e){a.guid=e;h("Callout",a)};this.getWrapper=function(){return A(a,"createLightbox","createCallout","createNotification")}});a.exports=e},Dlp:function(a,e,h){a.config={singleton:!0};var m=e("Class").extend(function(a){function k(a){if(a.origin===y){a=a.data;var b;try{b=JSON.parse(a)}catch(c){q.log("Can not parse message,\nbecause of: "+c.message+"\nerror with object:",a)}if(b)if(b.request)try{b.command&&
C[b.command](b)}catch(d){q.log('Can not execute "'+b.command+'" request command,\nbecause error occurred: '+d.message)}else if(b.error&&q.log(b.error),a=v[b.hash]){try{b.error?a.reject({error:b.error,data:b.data}):a.resolve(b.data)}catch(f){q.log(f)}delete v[b.hash]}}}function l(a,b){return{hash:ba(),command:a,data:b}}function f(a){try{window.parent.postMessage(JSON.stringify(a),y)}catch(b){q.log("Can not send event through post message,\nbecause of: "+b.message+"\nerror with object:",a);var c=v[a.hash];
c&&(c.reject({error:b,data:void 0}),delete v[a.hash])}}function b(a){var b=new m;v[a.hash]=b;f(a);return b.promise()}function c(a,b,c){return function(){for(var d={},f=0;f<c.length;f++)d[c[f]]=arguments[f];return a(l(b,d))}}var d=this,m=e("Deferred"),g=h("Action"),v={},L=new m,y=a.dlpOrigin,n={},C={console:function(a){a=a.data;q[a.method](a.message)},raiseEvent:function(a){n[a.data.handlerHash]()},"Action.sendActions":function(a){a=a.data.args;var b=a[2];a[2]=function(){f(l("runCallback",{handler:b}))};
g.sendActions.apply(g,a)}};this.parentReady=function(a){L.done(ia(a));return"resolved"===L.state()};this.proxy=function(a,c,d){return function(){var e={args:M(arguments),promised:d};return(d?b:f)(l(a+"."+c,e))}};this.trackClicks=function(a,b,c,d){f(l("Dom.trackClicks",{args:[a,b,c]}))};this.addListener=function(a,b,c){a=l("Dom.addListener",{selector:a,eventName:b});var d,e;for(e in n)if(n.hasOwnProperty(e)&&n[e]===c){d=e;break}e=a.data;d?e.handlerHash=d:(e.handlerHash=ba(),n[e.handlerHash]=c);f(a)};
this.removeListener=function(a,b,c){a=l("Dom.removeListener",{selector:a,eventName:b});for(var d in n)if(n.hasOwnProperty(d)&&n[d]===c){a.data.handlerHash=d;f(a);break}};this.checkNodeExist=c(b,"checkNodeExist",["selector"]);this.navigateTo=c(f,"navigateTo",["url"]);addEventListener?addEventListener("message",k,!1):attachEvent("onmessage",k);L=b(l("parentReady"));this.isDlpEnabled=function(){return!0};this.getWrapper=function(){return A(d,"isDlpEnabled")}});a.basic=function(){var a=this;this.getWrapper=
function(){return A(a,"isDlpEnabled")};this.isDlpEnabled=function(){return!1}};a.dlp=m},Modules:function(a,e,h){var m=e("Class");h=m.extend(function(){var a=this,h={cgapi:{},campaign:{alias:"Campaign",args:["campaignData"]},site:{alias:"Site"},renderer:{alias:"Renderer",args:["campaign"]},element:{},html:{},css:{},Deferred:{},when:{},events:{alias:"Events"},actions:{alias:"Action"},visitor:{alias:"Visitor"},modules:{alias:"Modules"},dom:{alias:"Dom"},cookies:{alias:"Cookies"},style:{alias:"Style"},
recommendations:{}},l=[],f=[],b={};this.define=function(a,b,h){if(!a||"string"!==typeof a)return q.log("Invalid module alias ( "+a+" )."),this;if(l[a])return l[a].reserved?q.log("Reserved name can not be used ( "+a+" )."):q.log("Module with this alias already defined  ( "+a+" )."),this;"function"===typeof b?(h=b,b={}):"string"===typeof b?b={extend:b}:b&&"object"===typeof b||(b={});"undefined"===typeof b.singleton&&(b.singleton=!0);"undefined"===typeof b.autoDefine&&(b.autoDefine=!0);if("undefined"!==
typeof b.extend&&("string"!==typeof b.extend||!b.extend))return q.log("Invalid parent alias ( "+b.extend+" )"),this;if(b.extend&&(!l[b.extend]||l[b.extend].reserved&&!l[b.extend].standard))return q.log("Parent module is not defined ( "+b.extend+" )"),this;if(!h||"function"!==typeof h)return q.log("Invalid module function ( "+a+" )."),this;var g;if(b.extend){var k=l[b.extend],z;k.reserved&&k.standard?(z=e(k.standard),"undefined"===typeof z.extend&&(z=m.extend(z)),g=k.args):z=k.func;h=z.extend(h)}else h=
m.extend(h);l[a]={func:h,extend:b.extend,extendArgs:g,reserved:!1,singleton:b.singleton,autoDefine:b.autoDefine};!0===b.autoDefine&&f.push(a);return this};this.require=function(a){if(a&&"string"===typeof a){var d=l[a];if(d&&!0!==d.reserved){a=d.instance;if(!a||!d.singleton)if(d.extendArgs){var f=[],e;for(e in d.extendArgs)d.extendArgs.hasOwnProperty(e)&&f.push(b[d.extendArgs[e]]);var h=function(){h.prototype=d.func.prototype;return d.func.apply(this,f)};a=new h}else a=new d.func;if(d.singleton){d.instance=
a;e={};var k=a,m;for(m in k)k.hasOwnProperty(m)&&(e[m]="function"===typeof k[m]?function(a){return function(){return k[a].apply(k,arguments)}}(m):k[m]);a=e}return a}q.log("Module is not registered ( "+a+" ).")}else q.log("Invalid module alias ( "+a+" ).")};this.getWrapper=function(c){c&&(b=c);return A(a,"define","require")};this.mergeInstances=function(b){b=b||{};for(var d in f)if(f.hasOwnProperty(d)){var e=f[d];b[e]||(b[e]=a.require(e))}return b};(function(){for(var a in h)if(h.hasOwnProperty(a)){var b=
h[a];l[a]=b&&b.alias?{reserved:!0,standard:b.alias,args:b.args}:{reserved:!0}}}).call(a)});a.exports=h},Vcb:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(a){var e=this;a=(a=a.vcbParams)||{isVcbActive:!1,maxZindex:12E5,registerLoop:function(){},useZindex:function(){return!0},registerClickAction:function(){return null}};O(a,function(a,h){e[h]=a})});a.exports=e},Recommendations:function(a,e,h){a.config={singleton:!1};var m=e("Class").extend(function(a){var k=this,l=h("CGApi"),
f=e("Deferred");this.setCategoryFilter=function(a,c,d){l.setCategoryFilter(a,c,d);return this};this.setProductFilter=function(a,c,d){l.setProductFilter(a,c,d);return this};this.requestPage=function(a){var c=f();l.request(a,function(a){a?c.resolve():c.reject()});return c.promise()};this.getProducts=function(){return a};this.getWrapper=function(){return A(k,"setCategoryFilter","setProductFilter","requestPage","getProducts")}});a.exports=m}};mmInitCallback(function(a,e,h){new function(a,e,h,l){function f(){var a=
location.search;if(window.parent!==window.self&&-1!==a.indexOf("original-url")&&(a=a.replace(/^\?/,"").split("&"),a=Z(a,function(a){return 0===a.indexOf("original-url")}))){var b,c;try{b=decodeURIComponent(a).split("=").slice(1).join("="),c=/http(s)?:\/\/.*?([^/]|$)+/.exec(b)[0]}catch(d){return}return c}}function b(a,b,c){function d(a){a.apply({},e)}c=c.replace(/[^a-z0-9_]*/gi,"");b=w.mergeInstances(b);var f=[],e=[];I(l.scriptArgumentsWrapper)&&(b=l.scriptArgumentsWrapper(b));for(var g in b)b.hasOwnProperty(g)&&
(f.push(g),e.push(b[g]));a="var applier = arguments[2];var scriptName = arguments[1];function "+c+"(){\nfunction inner_"+c+"("+f.join(",")+"){\n"+a+"\n}try {\n applier(inner_"+c+");\n} catch (e) {\ne.message = 'Error in '+scriptName+': ' + e.message;\nconsole.error(e);\n};};\n"+c+"();//# sourceURL="+c+".js";try{la.apply({},[a,c,d])}catch(h){h.message="Error in "+c+": "+h.message,q.error(h)}}function c(a){return"1.10"===a.HighLevelApiVersion}function d(a){a=B.require("Renderer",a);a.constructor=void 0;
return a}function p(a){var b=y();b.modules=w.getWrapper(a);b.campaign=a.campaign.getContext();b.renderer=d(a.campaign);return b}function g(a){if(a=r[a])return a=p({campaign:a}),a=w.mergeInstances(a)}function v(){var a=A();return a=w.mergeInstances(a)}function A(){var a=y();a.modules=w.getWrapper({});return a}function y(){return{site:x.getContext(),Deferred:B.requireClass("Deferred"),when:B.requireClass("When"),events:G.events.getWrapper(),actions:B.require("Action").getWrapper(),visitor:B.require("Visitor").getWrapper(),
dom:B.require("Dom").getWrapper(),widgets:B.require("Widgets").getWrapper(),dlp:B.require("Dlp").getWrapper(),cookies:B.require("Cookies").getWrapper(),recommendations:B.require("Recommendations",K).getWrapper()}}function n(d){u||(x=B.require("Site"),w=B.require("Modules"),u=!0);if(!l.skipPersistentData)for(var f=d.PersistData||[],e=f.length;e--;)a.setParam(f[e].Name,f[e].Value,a.baseStorage.storeStrategy.persistent,f[e].Expiration);var e,f=[],h=Y(d.Campaigns||[],c),k=Y(d.Scripts||[],c),n=B.requireClass("Campaign");
for(e=0;e<k.length;e++)f.push({script:k[e]});for(e=0;e<h.length;e++){k=h[e].Name;r[k]?r[k].updateData(h[e]):r[k]=new n(h[e]);K[k]=r[k].getRecommendations();for(var q=0;q<h[e].Scripts.length;q++)f.push({script:h[e].Scripts[q],campaign:r[k],campaignData:h[e]})}x.setPageExperiences(d.GenInfo||{});H=d.ServerAttributes;f.sort(function(a,b){return a.script.Order-b.script.Order});for(e=0;e<f.length;e++)d=f[e].script.Data,h=f[e].script.Name,(n=f[e].campaign)?(k=f[e].campaignData,b(d,p(f[e],{campaignData:k,
campaign:n}),k.Name+"_"+h)):b(d,A(),"Site_"+h);l.debug&&(l.debug["1.10"]={context:{getSiteScriptArguments:v,getCampaignScriptArguments:g}})}l=l||{};var G=this,t=[1,0];if(a.version.split(".")[0]!=t[0]||a.version.split(".")[1]<t[1])q.log("Loader have non compatible version with High level API.");else{var H={},t=f(),B=new ka({Engine:G},h,{isDlpEnabled:!C(t),dlpOrigin:t,vcbParams:l.vcbParams,cookieDomain:a.calcCookieDomain||a.cookie_domain||window.location.hostname.replace(/^www\./i,""),isBaseStorageSecure:a.baseStorage.isSecure,
moduleExtensions:l.moduleExtensions});B.addModule("BaseStorage",function(b){b.config={singleton:!1};b.exports=function(b){return a.baseStorage(b.namespace)}});B.addModule("Engine",function(a){a.config={singleton:!0}});var J=B.require("BaseStorage",{namespace:"mmengine"}),D={persistent:0,deferredRequest:1,request:2,page:3};this.storeStrategy=D;var F=[];F[D.page]={};F[D.request]={};var r={},x,w,u,K={};this.setParam=function(b,c,d,e){if(l.useLoaderStorage)a.setParam(b,c,d,e);else switch(d){case D.persistent:case D.deferredRequest:a.setParam(b,
c,d);break;case D.request:case D.page:F[d][b]=c;break;default:q.log("Unknown store strategy: "+d)}};this.getParam=function(b,c){if(l.useLoaderStorage)return a.getParam(b,c);switch(c){case D.persistent:case D.deferredRequest:return a.getParam(b,c);case D.request:case D.page:return F[c][b];default:q.log("Unknown store strategy: "+c)}};this.setData=function(a,b,c){J.set(a,b,c)};this.getData=function(a){return J.get(a)};this.clearData=function(a){J.set(a,null,-1)};this.getServerAttrs=function(){return H};
this.CGRequest=function(b){var c;l.useLoaderStorage||(c=a.mergeParams(F[D.page],F[D.request]),F[D.request]={});a.CGRequest(function(a){I(b)&&b(a)},c)};this.runElementScript=function(a,c,e,f){c=a.getElement(c);var g=y();g.modules=w.getWrapper();g.campaign=a.getContext();g.renderer=d(a);g.element=c.clone();g.html=e.html;g.css=e.css;g.recommendations=B.require("Recommendations",a).getWrapper();b(f,g,a.getName()+"_"+c.Name+"_"+c.VariantName)};this.events=B.require("Events");l.skipResponseProcessing||
n(e);a.on("response",n)}}(a,e,ma,h)})})()})();